# Generated by Django 4.1 on 2022-08-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phoneotp_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='logged',
            field=models.BooleanField(default=False, help_text='If otp verification got successful'),
        ),
    ]
