# Generated by Django 4.1 on 2022-08-31 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='phone',
            new_name='user',
        ),
    ]
