# Generated by Django 4.1 on 2022-09-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_phone_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='recored',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
